//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfRename.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfRename.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About WpfRename.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to © 2026 WpfRename Project.
        /// </summary>
        internal static string AboutCopyright {
            get {
                return ResourceManager.GetString("AboutCopyright", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WPF reimplementation of PowerToys PowerRename
        ///Modern file batch renaming tool.
        /// </summary>
        internal static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GitHub Repository.
        /// </summary>
        internal static string AboutGitHub {
            get {
                return ResourceManager.GetString("AboutGitHub", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MIT License.
        /// </summary>
        internal static string AboutLicense {
            get {
                return ResourceManager.GetString("AboutLicense", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WpfRename - File Batch Renaming Tool.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lowercase.
        /// </summary>
        internal static string CaseLower {
            get {
                return ResourceManager.GetString("CaseLower", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string CaseNone {
            get {
                return ResourceManager.GetString("CaseNone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Case Sensitive.
        /// </summary>
        internal static string CaseSensitiveCheckBox {
            get {
                return ResourceManager.GetString("CaseSensitiveCheckBox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title Case.
        /// </summary>
        internal static string CaseTitle {
            get {
                return ResourceManager.GetString("CaseTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Case Transform:.
        /// </summary>
        internal static string CaseTransformLabel {
            get {
                return ResourceManager.GetString("CaseTransformLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Uppercase.
        /// </summary>
        internal static string CaseUpper {
            get {
                return ResourceManager.GetString("CaseUpper", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string ClearButton {
            get {
                return ResourceManager.GetString("ClearButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Name.
        /// </summary>
        internal static string ColumnNewName {
            get {
                return ResourceManager.GetString("ColumnNewName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Original Name.
        /// </summary>
        internal static string ColumnOriginalName {
            get {
                return ResourceManager.GetString("ColumnOriginalName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeletePresetButton {
            get {
                return ResourceManager.GetString("DeletePresetButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string DialogCancelButton {
            get {
                return ResourceManager.GetString("DialogCancelButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string DialogSaveButton {
            get {
                return ResourceManager.GetString("DialogSaveButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Access denied: {0}.
        /// </summary>
        internal static string ErrorAccessDenied {
            get {
                return ResourceManager.GetString("ErrorAccessDenied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Directory not found: {0}.
        /// </summary>
        internal static string ErrorDirectoryNotFound {
            get {
                return ResourceManager.GetString("ErrorDirectoryNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File not found: {0}.
        /// </summary>
        internal static string ErrorFileNotFound {
            get {
                return ResourceManager.GetString("ErrorFileNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression pattern.
        /// </summary>
        internal static string ErrorInvalidRegex {
            get {
                return ResourceManager.GetString("ErrorInvalidRegex", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rename operation failed: {0}.
        /// </summary>
        internal static string ErrorRenameOperation {
            get {
                return ResourceManager.GetString("ErrorRenameOperation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File List (Drag &amp; Drop files or folders here):.
        /// </summary>
        internal static string FileListLabel {
            get {
                return ResourceManager.GetString("FileListLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Options:.
        /// </summary>
        internal static string OptionsLabel {
            get {
                return ResourceManager.GetString("OptionsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preset:.
        /// </summary>
        internal static string PresetLabel {
            get {
                return ResourceManager.GetString("PresetLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string RenameButton {
            get {
                return ResourceManager.GetString("RenameButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replace:.
        /// </summary>
        internal static string ReplaceLabel {
            get {
                return ResourceManager.GetString("ReplaceLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text to replace with.
        /// </summary>
        internal static string ReplacePlaceholder {
            get {
                return ResourceManager.GetString("ReplacePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Available variables:
        ///${count} - Enumeration (options: start, step, digits)
        ///${now} - Current date/time (format: yyyy-MM-dd)
        ///${created} - File creation date
        ///${modified} - File modification date
        ///
        ///Example: IMG_${count:start=1,digits=3} → IMG_001, IMG_002....
        /// </summary>
        internal static string ReplaceTooltip {
            get {
                return ResourceManager.GetString("ReplaceTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save Preset.
        /// </summary>
        internal static string SavePresetButton {
            get {
                return ResourceManager.GetString("SavePresetButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter preset name:.
        /// </summary>
        internal static string SavePresetDialogMessage {
            get {
                return ResourceManager.GetString("SavePresetDialogMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter preset name.
        /// </summary>
        internal static string SavePresetDialogPlaceholder {
            get {
                return ResourceManager.GetString("SavePresetDialogPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save Preset.
        /// </summary>
        internal static string SavePresetDialogTitle {
            get {
                return ResourceManager.GetString("SavePresetDialogTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        internal static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text to search.
        /// </summary>
        internal static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} items renamed.
        /// </summary>
        internal static string StatusRenamed {
            get {
                return ResourceManager.GetString("StatusRenamed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} items selected.
        /// </summary>
        internal static string StatusItemsSelected {
            get {
                return ResourceManager.GetString("StatusItemsSelected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string UndoButton {
            get {
                return ResourceManager.GetString("UndoButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use Regular Expression.
        /// </summary>
        internal static string UseRegexCheckBox {
            get {
                return ResourceManager.GetString("UseRegexCheckBox", resourceCulture);
            }
        }
    }
}
